/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuenosAires.BodegaBA.Vistas;

/**
 *
 * @author Liz
 */
public class VistaOpcionesBodega extends javax.swing.JFrame {

    /**
     * Creates new form VistaOpcionesBodega
     */
    public VistaOpcionesBodega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m_opcionesbodega = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_agregarproducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_consultanwo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bodega Buenos Aires");

        jMenu1.setText("Bodega");

        mi_agregarproducto.setText("Agregar Producto/Stock");
        mi_agregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarproductoActionPerformed(evt);
            }
        });
        jMenu1.add(mi_agregarproducto);

        m_opcionesbodega.add(jMenu1);

        jMenu2.setText("Anwo");

        mi_consultanwo.setText("Consulta/ Reserva Anwo");
        mi_consultanwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consultanwoActionPerformed(evt);
            }
        });
        jMenu2.add(mi_consultanwo);

        m_opcionesbodega.add(jMenu2);

        setJMenuBar(m_opcionesbodega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_consultanwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consultanwoActionPerformed
        VistaInventarioAnwo va = new VistaInventarioAnwo();
        va.setVisible(true);
    }//GEN-LAST:event_mi_consultanwoActionPerformed

    private void mi_agregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_agregarproductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOpcionesBodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar m_opcionesbodega;
    private javax.swing.JMenuItem mi_agregarproducto;
    private javax.swing.JMenuItem mi_consultanwo;
    // End of variables declaration//GEN-END:variables
}
